# Generated by Django 4.1.5 on 2023-03-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
