# Generated by Django 4.1.5 on 2023-03-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('orders', '0003_author_remove_books_author_name_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
