# Generated by Django 4.1.5 on 2023-03-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_books_readers_alter_books_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'Ok'), (2, 'Good'), (3, 'Amazing'), (4, 'Incredible'), (5, 'Awesome')], null=True),
        ),
    ]
