# Generated by Django 4.1.5 on 2023-03-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_book_userbookrelation_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelation',
            old_name='books',
            new_name='book',
        ),
    ]
