# Generated by Django 4.1.5 on 2023-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_books_userbookrelation_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
